import React, { useState } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  Share,
  Alert,
  StatusBar,
  Dimensions,
} from 'react-native';
import {
  Text,
  Button,
  Surface,
  ProgressBar,
  Divider,
  IconButton,
} from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';

import { useAppStore } from '../store/appStore';
import { logAnalysisResult } from '../services/firebaseService';

const { width } = Dimensions.get('window');

const MODEL_DESCRIPTIONS = {
  model1: 'Face landmarks and detection quality analysis',
  model2: 'Deep forensics neural network for manipulation detection',
  model3: 'Liveness check based on texture and micro-expressions',
  model4: 'Facial symmetry and structural consistency analysis',
};

export default function ResultsScreen({ navigation, route }) {
  const { result } = route.params;
  const [sharing, setSharing] = useState(false);
  
  const currentAnalysis = useAppStore((state) => state.currentAnalysis);

  const isProbablyDeepfake = result.isProbablyDeepfake;
  const confidence = result.confidence;

  // Determine verdict color
  const verdictColor = isProbablyDeepfake ? '#FF6B6B' : '#10B981';
  const verdictBgColor = isProbablyDeepfake ? '#FF6B6B15' : '#10B98115';

  const generateReport = () => {
    const timestamp = new Date(result.timestamp).toLocaleString();
    const report = `
═══════════════════════════════════════════════════════
                 DEEPFLY ANALYSIS REPORT
═══════════════════════════════════════════════════════

📅 Analysis Date: ${timestamp}
🔬 Method: Ensemble ML (4 Models)
⏱️ Processing Time: ${result.processingTime.toFixed(2)} seconds

───────────────────────────────────────────────────────
                      VERDICT
───────────────────────────────────────────────────────

${isProbablyDeepfake ? '⚠️ LIKELY DEEPFAKE' : '✅ LIKELY AUTHENTIC'}

Confidence Score: ${confidence}%

───────────────────────────────────────────────────────
                   MODEL BREAKDOWN
───────────────────────────────────────────────────────

📊 Model 1 - Face Detection
   Score: ${result.model1}%
   ${MODEL_DESCRIPTIONS.model1}

📊 Model 2 - Deep Forensics
   Score: ${result.model2}%
   ${MODEL_DESCRIPTIONS.model2}

📊 Model 3 - Liveness Check
   Score: ${result.model3}%
   ${MODEL_DESCRIPTIONS.model3}

📊 Model 4 - Symmetry Analysis
   Score: ${result.model4}%
   ${MODEL_DESCRIPTIONS.model4}

───────────────────────────────────────────────────────
                  TECHNICAL DETAILS
───────────────────────────────────────────────────────

👤 Faces Detected: ${result.faces}
🖼️ File Type: ${currentAnalysis?.fileType || 'Unknown'}
📁 File Name: ${currentAnalysis?.fileInfo?.name || 'Unknown'}

───────────────────────────────────────────────────────
                     DISCLAIMER
───────────────────────────────────────────────────────

This analysis is provided for informational purposes only.
Results are based on AI/ML models and may not be 100% accurate.
False positives and negatives are possible.

Generated by DeepFly - AI-Powered Deepfake Detector
All processing performed on-device for privacy.

═══════════════════════════════════════════════════════
`.trim();

    return report;
  };

  const shareReport = async () => {
    try {
      setSharing(true);
      const report = generateReport();
      
      // Try native share first
      const result = await Share.share({
        message: report,
        title: 'DeepFly Analysis Report',
      });

      if (result.action === Share.sharedAction) {
        console.log('Report shared successfully');
      }
    } catch (error) {
      console.error('Share error:', error);
      Alert.alert('Error', 'Failed to share report. Please try again.');
    } finally {
      setSharing(false);
    }
  };

  const saveReportToFile = async () => {
    // Use the same share functionality for saving
    await shareReport();
  };

  const handleGoHome = () => {
    // Log to Firebase (optional)
    logAnalysisResult(result);
    
    // Navigate to home
    navigation.popToTop();
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <StatusBar barStyle="light-content" />

      {/* Verdict Card */}
      <Surface
        style={[styles.verdictCard, { backgroundColor: verdictBgColor }]}
        elevation={3}
      >
        <View style={styles.verdictIconContainer}>
          <MaterialCommunityIcons
            name={isProbablyDeepfake ? 'alert-circle' : 'check-circle'}
            size={64}
            color={verdictColor}
          />
        </View>
        
        <Text style={[styles.verdictText, { color: verdictColor }]}>
          {isProbablyDeepfake ? '⚠️ Likely Deepfake' : '✅ Likely Authentic'}
        </Text>
        
        <Text style={styles.confidenceLabel}>Confidence Score</Text>
        
        <Text style={[styles.confidenceValue, { color: verdictColor }]}>
          {confidence}%
        </Text>
        
        <View style={styles.confidenceBarContainer}>
          <ProgressBar
            progress={confidence / 100}
            color={verdictColor}
            style={styles.confidenceBar}
          />
        </View>
        
        <Text style={styles.verdictSubtext}>
          {isProbablyDeepfake
            ? 'This media shows signs of potential manipulation or synthetic generation.'
            : 'This media appears to be authentic with no significant manipulation detected.'}
        </Text>
      </Surface>

      {/* Model Breakdown */}
      <Text style={styles.sectionTitle}>Model Breakdown</Text>
      
      {[
        { key: 'model1', name: 'Face Detection', icon: 'face-recognition', score: result.model1 },
        { key: 'model2', name: 'Deep Forensics', icon: 'magnify', score: result.model2 },
        { key: 'model3', name: 'Liveness Check', icon: 'eye', score: result.model3 },
        { key: 'model4', name: 'Symmetry Analysis', icon: 'chart-line', score: result.model4 },
      ].map((model, index) => (
        <Surface key={model.key} style={styles.modelCard} elevation={2}>
          <View style={styles.modelHeader}>
            <View style={styles.modelIconContainer}>
              <MaterialCommunityIcons
                name={model.icon}
                size={24}
                color="#FF6B6B"
              />
            </View>
            <View style={styles.modelInfo}>
              <Text style={styles.modelName}>{model.name}</Text>
              <Text style={styles.modelDescription}>
                {MODEL_DESCRIPTIONS[model.key]}
              </Text>
            </View>
            <Text style={styles.modelScore}>{model.score}%</Text>
          </View>
          <ProgressBar
            progress={model.score / 100}
            color={model.score > 70 ? '#FF6B6B' : model.score > 40 ? '#F59E0B' : '#10B981'}
            style={styles.modelProgressBar}
          />
        </Surface>
      ))}

      {/* Technical Details */}
      <Text style={styles.sectionTitle}>Technical Details</Text>
      
      <Surface style={styles.detailsCard} elevation={2}>
        <View style={styles.detailRow}>
          <MaterialCommunityIcons name="account-group" size={20} color="#808080" />
          <Text style={styles.detailLabel}>Faces Detected</Text>
          <Text style={styles.detailValue}>{result.faces}</Text>
        </View>
        
        <Divider style={styles.detailDivider} />
        
        <View style={styles.detailRow}>
          <MaterialCommunityIcons name="timer" size={20} color="#808080" />
          <Text style={styles.detailLabel}>Processing Time</Text>
          <Text style={styles.detailValue}>{result.processingTime.toFixed(2)}s</Text>
        </View>
        
        <Divider style={styles.detailDivider} />
        
        <View style={styles.detailRow}>
          <MaterialCommunityIcons name="chip" size={20} color="#808080" />
          <Text style={styles.detailLabel}>Method</Text>
          <Text style={styles.detailValue}>Ensemble ML (4 models)</Text>
        </View>
        
        <Divider style={styles.detailDivider} />
        
        <View style={styles.detailRow}>
          <MaterialCommunityIcons name="calendar" size={20} color="#808080" />
          <Text style={styles.detailLabel}>Analyzed</Text>
          <Text style={styles.detailValue}>
            {new Date(result.timestamp).toLocaleDateString()}
          </Text>
        </View>
      </Surface>

      {/* Score Interpretation */}
      <Surface style={styles.interpretationCard} elevation={1}>
        <Text style={styles.interpretationTitle}>📊 Score Interpretation</Text>
        <View style={styles.interpretationRow}>
          <View style={[styles.interpretationDot, { backgroundColor: '#10B981' }]} />
          <Text style={styles.interpretationText}>0-40%: Likely authentic</Text>
        </View>
        <View style={styles.interpretationRow}>
          <View style={[styles.interpretationDot, { backgroundColor: '#F59E0B' }]} />
          <Text style={styles.interpretationText}>40-70%: Inconclusive</Text>
        </View>
        <View style={styles.interpretationRow}>
          <View style={[styles.interpretationDot, { backgroundColor: '#FF6B6B' }]} />
          <Text style={styles.interpretationText}>70-100%: Likely deepfake</Text>
        </View>
      </Surface>

      {/* Action Buttons */}
      <View style={styles.actionsContainer}>
        <Button
          mode="outlined"
          onPress={shareReport}
          style={styles.actionButton}
          textColor="#FF6B6B"
          icon="share"
          loading={sharing}
        >
          Share Report
        </Button>
        
        <Button
          mode="outlined"
          onPress={saveReportToFile}
          style={styles.actionButton}
          textColor="#FF6B6B"
          icon="download"
          loading={sharing}
        >
          Save Report
        </Button>
      </View>

      <Button
        mode="contained"
        onPress={handleGoHome}
        style={styles.homeButton}
        contentStyle={styles.homeButtonContent}
        labelStyle={styles.homeButtonLabel}
        icon="home"
      >
        Back to Home
      </Button>

      {/* Disclaimer */}
      <Text style={styles.disclaimer}>
        ⚠️ This analysis is for informational purposes only. AI-based detection 
        may produce false positives or negatives. Results should not be used as 
        definitive proof of authenticity or manipulation.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0D0D0D',
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  verdictCard: {
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#252525',
  },
  verdictIconContainer: {
    marginBottom: 16,
  },
  verdictText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  confidenceLabel: {
    fontSize: 12,
    color: '#808080',
    marginBottom: 4,
  },
  confidenceValue: {
    fontSize: 56,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  confidenceBarContainer: {
    width: '100%',
    marginBottom: 16,
  },
  confidenceBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#25252580',
  },
  verdictSubtext: {
    fontSize: 13,
    color: '#A0A0A0',
    textAlign: 'center',
    lineHeight: 19,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    marginTop: 8,
  },
  modelCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#252525',
  },
  modelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  modelIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FF6B6B15',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  modelInfo: {
    flex: 1,
  },
  modelName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  modelDescription: {
    fontSize: 11,
    color: '#808080',
  },
  modelScore: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  modelProgressBar: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#252525',
  },
  detailsCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#252525',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  detailLabel: {
    flex: 1,
    fontSize: 14,
    color: '#A0A0A0',
    marginLeft: 12,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  detailDivider: {
    backgroundColor: '#252525',
  },
  interpretationCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#252525',
  },
  interpretationTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  interpretationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  interpretationDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 10,
  },
  interpretationText: {
    fontSize: 13,
    color: '#808080',
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
    marginHorizontal: 4,
    borderColor: '#FF6B6B',
    borderRadius: 12,
  },
  homeButton: {
    backgroundColor: '#FF6B6B',
    borderRadius: 12,
    marginBottom: 20,
  },
  homeButtonContent: {
    height: 52,
  },
  homeButtonLabel: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  disclaimer: {
    fontSize: 11,
    color: '#606060',
    textAlign: 'center',
    lineHeight: 16,
    paddingHorizontal: 8,
  },
});

